spring:
  application:
    name: jasper-modular-sample
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

jasper:
  modular:
    base-package: com.chaykin.jasper.sample

